version: "2"
services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      zk_id: "1"

  kafka:
    hostname: kafka
    container_name: kafka
    image: confluentinc/cp-kafka:5.0.0
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  schema-registry:
    hostname: schema-registry
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:5.0.0
    links:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

  client:
    image: confluentinc/cp-kafka:5.0.0
    container_name: client
    depends_on:
    - kafka
    hostname: kafka-create-topics
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b kafka:9092 1 20 && \
                       kafka-topics --create --topic itop --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 && \
                       kafka-topics --create --topic otop --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 && \
                       (java -cp /d/stream/target/stream-1.0-SNAPSHOT-shaded.jar io.lbg.brave.kafka.streams.example.TheStream&) &&
                       (java -cp /d/stream/target/stream-1.0-SNAPSHOT-shaded.jar io.lbg.brave.kafka.streams.example.TheClient&) &&
                       while true ; do sleep 1000 ; done'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    volumes:
      - .:/d
